scripts/check.mjs
src-tauri/src/cmds.rs
src-tauri/src/core/mod.rs
src-tauri/src/core/win_uwp.rs
src-tauri/src/main.rs
src/components/setting/setting-clash.tsx
src/locales/en.json
src/locales/ru.json
src/locales/zh.json
src/services/cmds.ts

添加了内置UWP loopback修改工具的支持，类似CFW同功能

feat: add UWP loopback tools

---

src-tauri/src/config/verge.rs
src-tauri/src/core/tray.rs
src/components/setting/setting-verge.tsx
src/locales/en.json
src/locales/ru.json
src/locales/zh.json
src/services/types.d.ts

feat: Config Tray Click Event

---

package.json
pnpm-lock.yaml
src-tauri/src/cmds.rs
src-tauri/src/config/profiles.rs
src-tauri/src/main.rs
src/components/profile/profile-item.tsx
src/pages/profiles.tsx
src/services/cmds.ts

feat: Support Drag to Reorder the Profile

---

src-tauri/src/core/tray.rs
src/components/setting/setting-verge.tsx

- Resolve https://github.com/wonfen/clash-verge-rev/pull/21#issuecomment-1833217517

feat: Support Disable Tray Click Event

---

.github/workflows/release.yml
scripts/check.mjs
scripts/updater.mjs

- #19 
Support both macos and linux

feat: Support cross-compiling to aarch64

---

src-tauri/src/config/verge.rs
src/components/setting/setting-clash.tsx

默认关闭Clash字段过滤，并在关闭时隐藏Clash设置中的Clash字段设置项

refactor: Hide Clash Field Option when Disable Filter

---

scripts/portable.mjs

refactor: Change Portable Config Path

---

src-tauri/src/core/sysopt.rs
src-tauri/src/feat.rs

fix: make port change set to system proxy immediately

---

scripts/windows/installer.nsi
src-tauri/tauri.windows.conf.json

https://github.com/clash-verge-rev/clash-verge-rev/issues/272
https://github.com/clash-verge-rev/clash-verge-rev/issues/267
点升级现在应该是100%出现文件冲突的情况，因为默认的升级程序只结束了主进程，没结束内核进程。请求管理员权限是因为服务模式用currentUser干不掉，另外win用户应该99.9%都是单用户。

fix: Solve the confliction issues on auto updater failure

---

src/components/profile/profile-item.tsx
src/pages/profiles.tsx

update profile ui

---

src/components/setting/setting-verge.tsx
src/pages/_layout.tsx
src/pages/_routers.tsx

fix issue: #705
fix it by change react router.

fix: missing proxy group delay check animations

---

src/components/layout/layout-control.tsx

fix: icon not change when toggle window maxinized

---

src/components/profile/confirm-viewer.tsx
src/components/setting/mods/web-ui-item.tsx

fix: #783 
稍微修改css样式来简单解决以下问题
- 确认删除对话框出现的滚动条
- web UI对话框的文本溢出导致的按钮不齐

style: adjust confirm dialog & web ui settings dialog

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/cmds.rs
src-tauri/src/core/tray.rs
src-tauri/tauri.conf.json
src/components/setting/mods/layout-viewer.tsx
src/services/cmds.ts

feat: support ico format for tray icon

---

src-tauri/src/cmds.rs
src-tauri/src/core/tray.rs

feat: support display current profile when the mouse is placed on the tray icon #782

feat: support display current profile when the mouse is placed on the tray icon #782

---

src/main.tsx

fixup: can't edit file

---

src/components/proxy/proxy-groups.tsx
src/components/proxy/proxy-render.tsx

避免频繁创建组件，提高性能
https://github.com/clash-verge-rev/clash-verge-rev/assets/46296997/25e65444-8d09-4162-bd82-12dd72540f43
https://github.com/clash-verge-rev/clash-verge-rev/assets/46296997/9f59c277-be29-4661-a4c4-b1f55cc543c6

perf: memoize the proxy col items

---

src-tauri/tauri.macos.conf.json

Closes: https://github.com/clash-verge-rev/clash-verge-rev/issues/1116

chore: Enable Ad Hoc signing on macOS

---

package.json
vite.config.ts

Fixes #1126.
Introduce `Object.hasOwn` polyfill from `core-js`.

fix(#1126): add `Object.hasOwn` polyfill

---

src/components/setting/mods/setting-comp.tsx
src/components/setting/setting-clash.tsx
src/components/setting/setting-verge.tsx
src/utils/is-async-function.ts

This PR add loading state to these 2 setting item below:
https://github.com/clash-verge-rev/clash-verge-rev/assets/53571741/ffa08292-f2df-4f03-b963-27ff69c5cc1d

feat(settings page): add loading state

---

src/services/api.ts

In #1203 the type is incorrect causing the build to fail. The PR fixes that.

fix(#1203): correct types

---

.github/workflows/release.yml

[New Feature] Integrate "Winget Releaser"

---

src/components/setting/mods/sysproxy-viewer.tsx

fix(#1387): avoid catastrophic backtracking

---

src-tauri/src/core/tray.rs

fix TUN icon is overwritten by system proxy icon

fix: fix TUN icon is overwritten by system proxy icon

---

src-tauri/tauri.macos.conf.json
src-tauri/tauri.windows.conf.json

Closes #1890 
see fixed pr on 1.x #930

fix: disable left click menu on macOS, Windows

---

src-tauri/src/core/clash_api.rs
src/components/setting/mods/misc-viewer.tsx
src/services/api.ts

change it to CloudFlare support iPv4&iPv6

chore: Replace test URL.

---

src-tauri/src/feat.rs
src/components/setting/setting-verge.tsx

add  proxy env varibale for Nushell
ref: https://www.nushell.sh/book/environment.html#setting-environment-variables

feat: add nushell env variable

---

src-tauri/src/cmds.rs
src-tauri/src/config/profiles.rs
src-tauri/src/core/tray/mod.rs
src-tauri/src/feat.rs

Relatived issues: #1845 #1801 #962
View:
Based on these changes, there is a addtional feature which switch specify proxies from the tray menu.
Let's PR this first :D

Feature: Switch Proxy Profile from Tray Menu

---

src-tauri/src/cmds.rs
src-tauri/src/feat.rs
src-tauri/src/lib.rs
src/pages/proxies.tsx
src/services/cmds.ts

Related issues: #2649
Before changes:
After changes:
Now you can switch proxy mode much much much more faster :D

perf: imporve clash mode switching performance on the main window

---

src/components/connection/connection-detail.tsx
src/components/connection/connection-table.tsx
src/locales/ar.json
src/locales/en.json
src/locales/fa.json
src/locales/id.json
src/locales/ru.json
src/locales/tt.json
src/locales/zh.json
src/services/types.d.ts

fix: use remoteDestination replace DestinationIP  in connection page, #2668

---

src-tauri/src/core/tray/mod.rs
src-tauri/src/core/tray/speed_rate.rs

feat: macos display colorful icon with speed rate

---

src-tauri/packages/macos/entitlements.plist
src-tauri/src/lib.rs
src-tauri/src/utils/resolve.rs
src-tauri/tauri.macos.conf.json

fix: macos dock icon and text display

---

package.json
src/components/proxy/proxy-groups.tsx
src/components/proxy/proxy-render.tsx

pdate package.json with improved dev and build scripts:
- Add fast-dev profile to development scripts
- Configure build:fast with fast-release profile
- Add clean command for cargo cleaning

chore: fast-dev and fast-build profile

---

.github/workflows/alpha.yml
.github/workflows/release.yml
CONTRIBUTING.md
package.json
scripts/alpha_version.mjs
scripts/portable.mjs
src-tauri/tauri.conf.json

- update doc for build portable by self
- remove 32bit platform from workflow
- update auto rename alpha version

workflow: remove 32-bit platform

---

src-tauri/src/cmd/proxy.rs
src-tauri/src/crate_mihomo_api/src/lib.rs
src-tauri/src/module/mihomo.rs
src-tauri/src/module/mod.rs

feat(mihomo): refactor MihomoManager for global access and improve proxy retrieval

---

src/components/layout/use-custom-theme.ts

feat: Add x-data-grid component localization

---

src/components/base/base-notice.tsx

typescript requires explicitly defined properties

fix: Notice @ts-ignore

---

src-tauri/src/core/timer.rs

- Add initialization flag to prevent duplicate timer initialization
- Improve logging for better debugging and monitoring
- Refactor async task function with proper error handling
- Add more detailed log messages throughout the timer lifecycle
----
背景：
解决 profile 定时更新问题：当前只会在应用启动的时候检查更新，并非定时更新的机制

refactor(timer): enhance timer initialization and task handling

---

src/pages/_layout.tsx

Hello!
Please note that the `.the-newbtn` UpdateButton is still NOT draggable as expected.

fix(layout): make app icon and name draggable

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src/components/setting/mods/sysproxy-viewer.tsx

https://github.com/clash-verge-rev/clash-verge-rev/issues/3370

[修复]修改代理设置后，如果修改之前代理是开启状态，自动重新应用代理设置。

---

src/components/setting/setting-clash.tsx

Fix issue when reinstalled the DNS overwrite button may show a wrong status.

---

src/pages/_layout.tsx

fix: 修正Linux系统窗口下页面白边和顶部圆角白底

---

src/components/layout/use-custom-theme.ts

fix:Linux displays white boxes, white dots and white bars

---

.prettierrc
package.json
pnpm-lock.yaml
src/components/connection/connection-detail.tsx
src/components/profile/profile-item.tsx
src/components/test/test-item.tsx
src/hooks/useServiceInstaller.ts

chore: update Prettier configuration and dependencies; refactor code formatting for consistency

---

.github/ISSUE_TEMPLATE/bug_report.yml

- Related #3927 
- 修复 `bug_report.yml` 中错误的 YAML 缩进
- 此问题导致最近几个新 Issues 未使用模板进行提问

Chore (ISSUE_TEMPLATE): 修复错误的 YAML 缩进 (bug_report.yml)

---

UPDATELOG.md
src/components/base/base-search-box.tsx

fix: the crash when inputting special characters in the search box

---

README.md

The script `check` was modified but the document was not updated in time

docs: how to develop locally

---

renovate.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/cmd/clash.rs
src-tauri/src/cmd/network.rs
src-tauri/src/cmd/profile.rs
src-tauri/src/cmd/runtime.rs
src-tauri/src/config/clash.rs
src-tauri/src/config/prfitem.rs
src-tauri/src/config/profiles.rs
src-tauri/src/config/runtime.rs
src-tauri/src/core/backup.rs
src-tauri/src/core/core.rs
src-tauri/src/enhance/chain.rs
src-tauri/src/enhance/field.rs
src-tauri/src/enhance/merge.rs
src-tauri/src/enhance/mod.rs
src-tauri/src/enhance/script.rs
src-tauri/src/enhance/seq.rs
src-tauri/src/enhance/tun.rs
src-tauri/src/feat/clash.rs
src-tauri/src/feat/config.rs
src-tauri/src/utils/help.rs
src-tauri/src/utils/init.rs

- **refactor: migrate from serde_yaml to serde_yaml_ng for improved YAML handling**
- **refactor: format code for better readability in DNS configuration**

refactor: migrate from serde_yaml to serde_yaml_ng for improved YAML handling

---

src-tauri/src/cmd/profile.rs

fix: #4937.
1. 修复 `delete_profile` 函数 —— 在成功删除 Profile 并刷新 clash 配置后，新增调用 `handle::Handle::notify_profile_changed(index)`
2. 修复 `create_profile` 函数 —— 在成功创建 Profile 后，新增调用 `handle::Handle::notify_profile_changed(uid.clone())`
3. 两处修改均增加了日志输出，用于记录通知发送的时机
此前前端 UI 在创建或删除 Profile 后不会自动更新。现在：
- 创建 Profile 时，后端会发送 `"profile-changed"` 事件通知
- 删除 Profile 时，后端会发送 `"profile-changed"` 事件通知
- 前端监听器接收到事件后会自动刷新 Profile 列表
- 无需再重启应用才能看到最新变化
该解决方案沿用了现有的 `import_profile` 函数中已验证可行的模式，保证了代码的一致性。

fix: ensure frontend sync after profile create/delete

---

src-tauri/src/feat/clash.rs
src-tauri/src/utils/resolve/mod.rs

改进了 `restart_app` 的错误处理，确保清理失败时错误会被正确上报，同时增加了用户通知。

fix: implement proper error handling for "Restart App" failures

---

src-tauri/src/feat/clash.rs

fix(tray): resolve "Restart App" failure on Windows

---

src-tauri/src/core/service.rs
src-tauri/src/core/win_uwp.rs

fix(windows): show UAC prompt for TUN service install/uninstall

---

src/components/home/current-proxy-card.tsx

feat: url test button for proxy card and type safety
