clash-verge-rev/clash-verge-rev

src/components/profile/editor-viewer.tsx
目前的脚本编辑窗口是固定宽度，不会随窗口自适应调节，编辑内容较长时不方便查看，修改为自适应宽度
=> feat: Update DialogContent width in EditorViewer

src-tauri/Cargo.lock, src-tauri/Cargo.toml
目前版本在非管理员身份下运行时，安装服务会报错，但实际已经安装成功了。Debug确定是由于runas 1.1.0版本错误返回了exit code导致的，降级到1.0.0可解决。
参考runas的issue  https://github.com/mitsuhiko/rust-runas/issues/13
=> fix: Downgrade runas to fix service install bug

src-tauri/src/core/tray.rs
=> fix: Tray Icon Tooltip is Empty

.github/workflows/release.yml, scripts/check.mjs, scripts/updater.mjs
添加了Windows 32位和Linux armv7支持，但是由于clash-verge所依赖的 [rquickjs](https://github.com/DelSkayn/rquickjs) 暂时还不支持armv7，所以先将相关脚本注释了。
- #25
=> feat: Add Windows x86 and Linux armv7 Support

scripts/check.mjs
mihomo already supported loong64, see [here](https://github.com/MetaCubeX/mihomo/pull/871)
=> feat: Add support for loong64

src-tauri/src/config/prfitem.rs, src-tauri/src/utils/help.rs
- 下拉订阅配置文件时，在服务端没有指定文件名时，使用URL的最后一段作为名称而非'Remote File'，和CFW行为保持一致。
=> feat: use url path's name as the default name fallback for subscription import without Content-Disposition header

src-tauri/src/config/prfitem.rs, src-tauri/src/utils/resolve.rs, src/components/profile/profile-viewer.tsx, src/locales/en.json, src/locales/ru.json, src/locales/zh.json, src/services/types.d.ts
For the remote profile, a new parameter 'danger_accept_invalid_certs' is added to allow invalid/expired certificates.
The parameter will be passed to the reqwest ClientBuilder.
Refer to [Reqwest Docs](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs)
Resol
=> Feat: resolves #438 provide a switch for allowing invalid certificates

src/components/layout/layout-item.tsx, src/pages/_layout.tsx, src/pages/_routers.tsx
Icon not working in `v1.5.5`, refactoring with React SVG Component.  @MystiPanda
|  before   | after  |
|  ----  | ----  |
| ![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/13595509/97b7c3a9-53a9-4854-b885-94545b407e18)  | ![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/13595509/fee3e866-3405-4ae1-bea5-3da3271f348f) |
=> tweak(ui): menu icon use svg component

src/components/rule/rule-item.tsx
Clash-meta has 2 reject policy, but only standard `REJECT` policy displayed as red color in the rules page.
=> fix: Set `REJECT-DROP` policy the same text color as `REJECT`

src/pages/_theme.tsx
mac端默认使用safair内核，之前的代码，font-family会以`, `结尾，mac用户设置的字体无效生效，之前的bug如图：
修复后：
win端无此问题。
=> fix: mac setting theme font-famil not working

src-tauri/src/feat.rs, src/components/setting/mods/stack-mode-switch.tsx
Now that Service mode has been supported for macOS as well, remove these platform-specific logic.
=> fixup! feat: Service Mode for Linux (#804)

src/components/layout/layout-traffic.tsx, src/components/proxy/proxy-groups.tsx, src/components/proxy/proxy-item-mini.tsx, src/components/proxy/proxy-item.tsx, src/components/proxy/proxy-render.tsx, src/hooks/use-websocket.ts, src/services/api.ts, src/services/types.d.ts
1. meta内核已在23年8月左右修复了url-test的fixed锁定清除问题[727](https://github.com/MetaCubeX/mihomo/issues/727)、[482](https://github.com/MetaCubeX/metacubexd/issues/482)、[693](https://github.com/MetaCubeX/mihomo/issues/693)、
2. meta内核官方Web UI [metacubexd](https://github.com/MetaCubeX/metacubexd)已支持url-test的手动选择，点击节点组的仪表盘测速将清除fixed
3. 手动选择url-test、fallback节点组中的节点，会将节点置为fixed
4. 目前verge节点组中没有任何indicator将fixed节点标识出来
1. 当存在fixed的节点时，且**fixed节点可用**，**会优先使用fixed节点，即使它的延迟比其他节点都要大**
2. 当不存在fixed的节点时，选择延迟最小的
3. 当调用接口`GET /group/${groupName}/delay`时,会清除fixed标记
1. 当存在fixed的节点时，将使用fixed节点作为当前选中节点
2. 当不存在fixed的节点时，将按照proxy配置定义的顺序找出第0个可用的节点
3. 当选中的节点不再可用时**发生故障转移 会自动清除fixed标记**，并重新找出第0个可用的节点
1. 启用URLTest类型的手动选择
2. 对于fixed的节点，使用📌角标标识出来，且当fixed不可用时标记置灰。用户可以得知这些节点将会优先选择（如果可用的话）。
3. 点击**headState的延迟测试wifi**按钮时，调用`GET …
=> feat: url-test支持手动选择、节点组fixed节点使用角标展示

src-tauri/tauri.macos.conf.json
Left-clicking on the system tray icon on macOS would open both the application panel and the menu. 
This PR avoids showing menu on left click.
=> fix: disable left click menu on macOS

src/main.tsx
- 关闭WebView默认的快捷键（例如：F5、CTRL+F搜索、CTRL+H、CTRL+R刷新），防止与编辑器快捷键产生冲突
- CTRL+SHIFT+I不受影响，依旧可以呼出DEV控制台
- 程序热键配置的快捷键不受影响
=> chore: disable WebView keyboard shortcuts

src-tauri/src/utils/resolve.rs, src/pages/profiles.tsx
- 在我的 Linux (Debian 12, Gnome) 上，无法使用粘贴按钮进行剪贴板的粘贴，使用 tauri 的 clipboard 就没问题
- Linux 上不支持 `set_shadow`  方法
=> fix: use tauri clipboard

package.json, pnpm-lock.yaml, src-tauri/src/utils/resolve.rs, src/assets/styles/page.scss, src/components/profile/profile-item.tsx, src/components/profile/profile-more.tsx, src/components/test/test-item.tsx, src/components/test/test-viewer.tsx, src/pages/profiles.tsx, src/pages/test.tsx
使用简单易上手的 sortablejs 替换 dnd 来实现拖拽排序，并添加以下功能：
- 测试页面修改 item 信息后导致 clash core 重启
https://github.com/clash-verge-rev/clash-verge-rev/assets/46296997/9e097dec-4990-4362-9bea-1e0f61b9a704
=> refactor: use sortablejs to implement drag and sort

src/pages/connections.tsx
语言使用中文，在宽度小于700px后，连接页面 `连接` 和 `关闭全部`显示如下图，与其他页面不相符：
修改后将 `连接` 和 `关闭全部` 以下图方式显示：
=> fix: 中文下连接页面的显示问题

package.json, pnpm-lock.yaml, src/components/layout/use-custom-theme.ts, src/components/layout/use-log-setup.ts, src/components/profile/editor-viewer.tsx, src/components/profile/profile-item.tsx, src/components/proxy/proxy-render.tsx, src/components/setting/mods/update-viewer.tsx, src/main.tsx, src/pages/_layout.tsx, src/pages/connections.tsx, src/pages/logs.tsx, src/pages/profiles.tsx, src/pages/settings.tsx, src/services/states.ts
Recoil is a powerful state management library designed for complicated use cases. But for `clash-verge-rev`, the most common usage of `recoil` is simply sharing states across the entire application or persists the state in `localStorage`. Those simple use cases don't require a heavy solution like `recoil`.
The PR replaces most recoil atoms with `React Context + React state` based solution and replaces persist states with a lightweight `useLocalStorage` hook (`useSyncExternalStore` based).
=> refactor: replace recoil

src/components/setting/mods/setting-comp.tsx, src/components/setting/setting-clash.tsx, src/components/setting/setting-verge.tsx
This PR makes those `SettingItems` which need to show a modal to do some further configs now can directly click the whole item body to show the modal.
https://github.com/clash-verge-rev/clash-verge-rev/assets/53571741/67d4ecc7-2434-4927-911a-cf4fd66f585f
=> feat: make `SettingItem` clickable

package.json, pnpm-lock.yaml, src/pages/connections.tsx, src/services/states.ts
`useLocalStorage`'s returned state will not be `null` if a default value is provided. The latest version of `foxact` has improved the typescript types to reflect this behavior.
=> refactor: simplify `useConnectionSetting`

package.json, pnpm-lock.yaml, src/components/layout/layout-traffic.tsx
- Update SWR to 2.x
- `useSWRSubscription` is only available in SWR >= 2.1.0
- https://swr.vercel.app/docs/subscription
- Refactor layout traffic / memory to use `useSWRSubscription`
- Introduce [`sockette`](https://github.com/lukeed/sockette) for creating WebSocket connections
- `sockette` is a 367-byte wrapper around WebSocket that has a built-in automatic reconnect feature.
=> chore: use swr subscription for layout traffic / memory

src/pages/logs.tsx, src/services/api.ts, src/services/cmds.ts
Replace multiple `Array#map` `Array#filter` chains with single `Array#reduce`.
The entire array will be iterated through on every `.map()`, `.filter()`, and `.reduce()` call. By replacing multiple `.map()` and `.filter()` with a single `.reduce()` call, the array will be iterated less frequently, thus improving the performance.
The improvement is most notable on the proxy list and log panel (where arrays' sizes could be huge).
=> perf: replace `Array#map` `Array#filter` chain w/ `Array#reduce`

src/components/profile/editor-viewer.tsx
- Hide the "Save" button when the editor view is read-only
- Make the "Cancel" button the primary color when the editor view is read-only
=> fix: hide save button in readonly editor view

src/components/layout/layout-traffic.tsx, src/utils/websocket.ts
In my previous PR #1202, I copied and pasted the `errorCount` and re-connect code between two `useSWRSubscription` calls.
The PR creates a wrapper around the Sockette to reduce the repeated code, enabling future migration to `useSWRSubscription`.
=> feat: add a wrapper around sockette w/ error retry

.github/workflows/alpha.yml, .github/workflows/release.yml
Continues from #1279, enable cache for webview2 as well.
=> ci: speed up cargo install by enabling cache (webview2)

src/components/profile/group-item.tsx, src/components/profile/profile-item.tsx, src/components/profile/proxy-item.tsx, src/components/profile/rule-item.tsx, src/components/test/test-item.tsx
When I drag box A to the position of box B, box B will cover box A:
Expected and fixed:
=> fix: dnd box z-index

src/components/test/test-item.tsx
when test url is updated, `TEST ALL` button still will test the old test url.
=> fix delay test error after updating test url

src/components/setting/mods/network-interface-viewer.tsx
perf AddressDisplay component padding
before
after
=> style: AddressDisplay padding

package.json, pnpm-lock.yaml, scripts/check.mjs, scripts/portable-fixed-webview2.mjs, scripts/portable.mjs, scripts/updatelog.mjs
Prefer Node.js built-in fs methods over `fs-extra`.
=> chore: drop fs-extra

src-tauri/src/core/tray.rs
=> fix: macOS tray icon not changed when using system proxy or tun mode

src-tauri/src/enhance/tun.rs
Dynamically set the `dns.ipv6` configuration based on whether IPv6 is enabled in the panel configuration.
=> 🐛 fix: Dynamically set IPv6 DNS configuration based on existing config

src-tauri/src/config/verge.rs, src-tauri/src/core/hotkey.rs, src-tauri/src/feat.rs, src-tauri/src/lib.rs, src/components/setting/mods/hotkey-viewer.tsx, src/locales/zh.json, src/services/types.d.ts
relatived issus: #2656 
When global hotkeys are disabled, you can only use shortcuts within the program window or when interacting with the tray menu.
=> Feature: Optionally enable global hotkeys

src-tauri/src/core/core.rs, src-tauri/src/core/health_check.rs, src/services/types.d.ts
fix: build time front cannot find IVergeConfig attribute enable_lite_mode
fix: macos switch protocol port or enable protocol port causes crash
=> fix: build front cannot find IvergeConfig.enable_lite_mode and macos port switching causes crash

scripts/check.mjs
After upgrading to a newer version of [https-proxy-agent](https://github.com/TooTallNate/proxy-agents), function calls will no longer be supported. 
```text
PS C:\Users\akioe\Desktop\code\clash-verge-rev> pnpm run check --force
> clash-verge@2.0.2 check C:\Users\akioe\Desktop\code\clash-verge-rev
> node scripts/check.mjs "--force"
task::verge-mihomo-alpha try 0 == proxyAgent is not a function
task::verge-mihomo-alpha try 1 == proxyAgent is not a function
task::verge-mihomo-alpha try 2 == proxyAgent is not a function
task::verge-mihomo-alpha try 3 == proxyAgent is not a function
task::verge-mihomo-alpha try 4 == proxyAgent is not a function
file:///C:/Users/akioe/Desktop/code/clash-verge-rev/scripts/check.mjs:88
options.agent = proxyAgent(httpProxy);
^
TypeError: proxyAgent is not a …
```
=> fix: check script https-proxy-agent error

.github/workflows/alpha.yml, package.json, scripts/alpha_version.mjs
**带来以下影响**
1. 设置页面verge version会显示 v2.0.4-2b01857
2. Alpha发版文件名会被改成类Clash.Verge_2.0.4-2b01857_x64-setup.exe
> 更新assets上传的文件名是匹配`*setup.exe` 或 `*.deb`
不影响上传流程
=> feat: auto rename alpha version

package.json, src-tauri/Cargo.toml
- Added fast compilation profiles in Cargo.toml
- fast-dev profile with max codegen units and disabled optimizations
- fast-release profile with debugging support and faster build time
- Added new npm scripts for quick development iterations
- dev:fast command for standard development without extra features
- build:fast command for quick release builds
- Updated default dev command to use verge-dev feature flag
- Both profiles retain debug symbols and disable stripping for better debugging
=> feat: add fast compilation options for development and release

src/components/proxy/proxy-groups.tsx, src/components/proxy/proxy-render.tsx
- Increased spacing in proxy-groups.tsx by adjusting the right position of the alphabet selector to provide better visual separation
- Enhanced spacing in proxy-render.tsx with larger margins and padding
- Increased group item margins from 8px to 10px with 16px horizontal spacing
- Expanded border radius from 8px to 10px for smoother appearance
- Improved ProxyHead component spacing with pl: 3, pr: 3.5
- Enhanced grid spacing in proxy collection items from 1 to 1.5
- Adjusted padding for better visual hierarchy
These changes create a more polished, spacious layout with improved readability and touch targets.
=> refactor: improve proxy group UI and spacing

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/config/api/mihomo.rs, src-tauri/src/config/api/mod.rs, src-tauri/src/config/mod.rs, src-tauri/src/enhance/seq.rs, src-tauri/src/model/api/common.rs, src-tauri/src/model/api/mihomo.rs, src-tauri/src/model/api/mod.rs, src-tauri/src/model/mod.rs, src-tauri/src/module/api/common.rs, src-tauri/src/module/api/mihomo.rs, src-tauri/src/module/api/mod.rs, src-tauri/src/module/mihomo.rs, src-tauri/src/module/mod.rs
• Introduce new API caller implementations for Mihomo in model and module layers.
• Add configuration and API integration files under /src-tauri/src/config/api and /src-tauri/src/model/api.
• Implement a singleton MihomoAPICaller with async API call support and integration tests.
• Create a new MihomoManager module to refresh and fetch proxies from the API.
• Update Cargo.lock and Cargo.toml with additional dependencies (async-trait, env_logger, mockito, tempfile, etc.) related to the Mihomo API support.
=> feat: add Mihomo API modules and manager

src/locales/en.json
This pull request corrects a typo in src/locales/en.json by replacing “than” with “then”, gives more accurate instructions.
=> chore: correct typo in src/locales/en.json

src/components/setting/mods/sysproxy-viewer.tsx
取消使用默认绕过选项且当绕过设置为空时则使用默认绕过填充绕过配置以便用户基于默认配置修改。
=> 修复一处编译错误，添加bypass的优化

src/components/setting/setting-verge-basic.tsx
=> fix: 关闭启动脚本 input 组件下划线

src-tauri/src/feat/window.rs, src-tauri/src/lib.rs
当前在macos上通过Dock或者关机的方式关闭应用时不会触发清理代理设置，这会导致无法正常联网。调试发现上述的退出方式会触发 *tauri::RunEvent::Exit** 事件，增加对该事件的处理。  
可能关联的issue: 
https://github.com/clash-verge-rev/clash-verge-rev/issues/3196
=> feat: clean proxy settings before exit

src-tauri/src/config/clash.rs
Include "https://yacd.metacubex.one", "https://metacubex.github.io", and "https://board.zash.run.place" to the list of allowed origins for both HTTP and WebSocket configurations.
=> feat(config): add new allowed origins for CORS in clash.rs

.github/ISSUE_TEMPLATE/bug_report.yml
- 修改 `bug_report.yml`
- 增加一段预置的格式模板，指引用户将日志粘贴在规范的 Code Block 中以保持日志原有的格式排版
- 使用 `<details />` 块以压缩日志片段，对于非 Contributors / Collaborators 用户友好，规避日志霸屏效果，简化爬楼。
- Related #3888 
在浏览 Issues 的过程中，发现项目提供的「问题反馈」模板在最后有要求用户提供日志，但禁止以文件的形式上传日志，必须将日志原文直接粘贴于 Issues Descriptions 中。
由于本项目用途的特殊性，多数提问者对 GitHub Flavored Markdown 了解并不多，且模板并未对此部分内容自动使用 Code Blocks 模式进行格式化，导致日志会被 GitHub 错误排版影响阅读。
对于其他希望参与 Issues 讨论的用户，用 Details 块将日志高度折叠压缩也能避免日志霸屏、方便快速爬楼。同时在内部嵌套预留 Code Block ，指引用户在预留的模板内指定位置粘贴日志文本。
=> chore (ISSUE_TEMPLATE): 修改问题反馈模板

.github/ISSUE_TEMPLATE/bug_report.yml
- 当前模板强依赖于用户把日志贴到正确的位置上
- 参考 WinGet 的问题模板，放弃日志折叠功能，强制用户以代码块形式粘贴日志
- Resolve #3974
=> Chore (ISSUE_TEMPLATE): 进一步优化问题反馈模板

src/components/base/base-search-box.tsx, src/locales/en.json, src/locales/zh.json
=> optimization: (fix: the crash when inputting special characters in the search box (#4026))

src-tauri/src/core/tray/mod.rs
还原原轻量模式
同时把轻量模式系统托盘id从entry_lightweight_mode改为lightweight_mode 避免歧义
=> 还原轻量模式的进入和退出行为

src-tauri/src/utils/resolve/mod.rs
fix [#4880](https://github.com/clash-verge-rev/clash-verge-rev/issues/4880).
确保运行时配置在核心管理器启动前已生成，解决可能出现的 `failed to get runtime config` 错误。
=> fix(init): ensure runtime config is ready before core manager startup
